Aqui debe ir todo el flujo del proceso

In [ ]:
!pip install kaggle --quiet

In [1]:
#importamos funciones para utilzar en nuestro flujo
import sys
import os
import pandas as pd

import pandas as pd
import os
import sys
import sqlite3
import requests
import time
import kaggle
from kaggle.api.kaggle_api_extended import KaggleApi
from pathlib import Path
from dotenv import load_dotenv #pip install python-dotenv
from googleapiclient.discovery import build
from google.oauth2 import service_account #pip install google-auth
from googleapiclient.http import MediaFileUpload
from google_auth_oauthlib.flow import InstalledAppFlow
from googleapiclient.discovery import build
from mimetypes import guess_type


ruta_utils = os.path.expanduser('~/Documents/IA/4_semestre/ing_de_datos/ing_datos/tools')
sys.path.append(ruta_utils)

import tools

#from tools import DRIVE_IDS
print(f"Tools importado correctamente")
print(f"Los métodos alojados en las herramientas son {dir(tools)}")

Tools importado correctamente
Los métodos alojados en las herramientas son ['BASE_DIR', 'DRIVE_IDS', 'InstalledAppFlow', 'KAGGLE_JSON_PATH', 'KaggleApi', 'MediaFileUpload', 'Path', 'RUTA_CARPETA_BASES_KAGGLE', 'RUTA_CARPETA_BASE_SQL', '__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__spec__', 'build', 'drive', 'glob', 'guess_type', 'kaggle', 'load_dotenv', 'os', 'pd', 'requests', 'service_account', 'sql', 'sqlite3', 'sys', 'tempfile', 'time']

In [3]:
#CONSULTAR BASES A DESCARGAR, 3 bases
tools.kaggle.consultar_bases_datos("Latest Data Science Job Salaries")

Buscando datasets en Kaggle: Latest Data Science Job Salaries
saurabhbadole/latest-data-science-job-salaries-2024
iamsouravbanerjee/data-science-salaries-2023
aliahmad69/data-science-salary-analysis-of-2020-2022
whenamancodes/data-professionals-salary-dataset-2022
zalizedata/us-work-visa-salary-dataset
hardestmarket/japan-human-capital-data-2026-3789-companies

In [5]:
tools.kaggle.consultar_bases_datos("The AI, ML, Data Science Salary")

Buscando datasets en Kaggle: The AI, ML, Data Science Salary
samithsachidanandan/the-global-ai-ml-data-science-salary-for-2025
adilshamim8/salaries-for-data-science-jobs
bismasajjad/global-ai-job-market-and-salary-trends-2025
alitaqishah/ai-jobs-market-2025-2026-salaries
abhishekjaiswal4896/ai-job-market-trends
cedricaubin/ai-ml-salaries
msjahid/global-ai-ml-and-data-science-salaries
uditjain13/ai-and-data-science-job-salaries-2026
joyshil0599/data-science-jobs-comprehensive-dataset
lorenzovzquez/data-jobs-salaries
elahehgolrokh/data-science-job-postings-with-salaries-2025
willianoliveiragibin/data-jobs-salaries
shambhurajejagadale/student-placement-and-career-success-dataset-2026
pratyushpuri/global-ai-job-market-trend-2025
crystalbaby/global-programming-languages-intelligence-dataset

In [6]:
tools.kaggle.consultar_bases_datos("Data Science, AI & ML Job Salaries")

Buscando datasets en Kaggle: Data Science, AI & ML Job Salaries
adilshamim8/salaries-for-data-science-jobs
bismasajjad/global-ai-job-market-and-salary-trends-2025
alitaqishah/ai-jobs-market-2025-2026-salaries
msjahid/global-ai-ml-and-data-science-salaries
cedricaubin/ai-ml-salaries
elahehgolrokh/data-science-job-postings-with-salaries-2025
samithsachidanandan/the-global-ai-ml-data-science-salary-for-2025
pratyushpuri/global-ai-job-market-trend-2025
willianoliveiragibin/data-jobs-salaries
mexwell/data-science-salary-data
debayank2024/ai-impact-on-jobs-and-salaries-2020-2026
uditjain13/ai-and-data-science-job-salaries-2026
meruvakodandasuraj/global-ai-adoption-and-workforce-impact-survey-24-26
sumeakash/ai-impact-on-job-sector
ahsanneural/tech-layoffs-and-hiring-trends-2025-2026

In [7]:
#DESCARGARGAMOS
bases = ['saurabhbadole/latest-data-science-job-salaries-2024',
         'samithsachidanandan/the-global-ai-ml-data-science-salary-for-2025',
         'adilshamim8/salaries-for-data-science-jobs']

for i in bases:
    tools.kaggle.descargar_datos(ref=i)

Descargando: saurabhbadole/latest-data-science-job-salaries-2024 en la carpeta /Users/memoblack1/Documents/IA/4_semestre/ing_de_datos/ing_datos/datasets/saurabhbadole_latest-data-science-job-salaries-2024
Dataset URL: https://www.kaggle.com/datasets/saurabhbadole/latest-data-science-job-salaries-2024
Descarga exitosa: saurabhbadole/latest-data-science-job-salaries-2024
  Carpeta       : /Users/memoblack1/Documents/IA/4_semestre/ing_de_datos/ing_datos/datasets/saurabhbadole_latest-data-science-job-salaries-2024
  Archivos CSV  : 1 (usado: DataScience_salaries_2025.csv)
  Dimensiones   : 93,597 filas x 11 columnas
  Columnas      : ['work_year', 'experience_level', 'employment_type', 'job_title', 'salary', 'salary_currency', 'salary_in_usd', 'employee_residence', 'remote_ratio', 'company_location', 'company_size']
Descargando: samithsachidanandan/the-global-ai-ml-data-science-salary-for-2025 en la carpeta /Users/memoblack1/Documents/IA/4_semestre/ing_de_datos/ing_datos/datasets/samithsachidanandan_the-global-ai-ml-data-science-salary-for-2025
Dataset URL: https://www.kaggle.com/datasets/samithsachidanandan/the-global-ai-ml-data-science-salary-for-2025
Descarga exitosa: samithsachidanandan/the-global-ai-ml-data-science-salary-for-2025
  Carpeta       : /Users/memoblack1/Documents/IA/4_semestre/ing_de_datos/ing_datos/datasets/samithsachidanandan_the-global-ai-ml-data-science-salary-for-2025
  Archivos CSV  : 1 (usado: salaries.csv)
  Dimensiones   : 88,584 filas x 11 columnas
  Columnas      : ['work_year', 'experience_level', 'employment_type', 'job_title', 'salary', 'salary_currency', 'salary_in_usd', 'employee_residence', 'remote_ratio', 'company_location', 'company_size']
Descargando: adilshamim8/salaries-for-data-science-jobs en la carpeta /Users/memoblack1/Documents/IA/4_semestre/ing_de_datos/ing_datos/datasets/adilshamim8_salaries-for-data-science-jobs
Dataset URL: https://www.kaggle.com/datasets/adilshamim8/salaries-for-data-science-jobs
Descarga exitosa: adilshamim8/salaries-for-data-science-jobs
  Carpeta       : /Users/memoblack1/Documents/IA/4_semestre/ing_de_datos/ing_datos/datasets/adilshamim8_salaries-for-data-science-jobs
  Archivos CSV  : 1 (usado: salaries.csv)
  Dimensiones   : 151,445 filas x 11 columnas
  Columnas      : ['work_year', 'experience_level', 'employment_type', 'job_title', 'salary', 'salary_currency', 'salary_in_usd', 'employee_residence', 'remote_ratio', 'company_location', 'company_size']

In [10]:
#CARGAR CSV A CARPETA KAGGLE EN DRIVE
drive_folder = tools.DRIVE_IDS["KAGGLE_DRIVE_FOLDER_ID"]
path = '/Users/memoblack1/Documents/IA/4_semestre/ing_de_datos/ing_datos/datasets/'
csvs = ['adilshamim8_salaries-for-data-science-jobs/salaries.csv',
        'samithsachidanandan_the-global-ai-ml-data-science-salary-for-2025/salaries.csv',
        'saurabhbadole_latest-data-science-job-salaries-2024/DataScience_salaries_2025.csv']
for i in csvs:
    new_path = str(path + i)
    tools.drive.cargar_archivo(drive_folder, new_path)

Please visit this URL to authorize this application: https://accounts.google.com/o/oauth2/auth?response_type=code&client_id=404263101909-0hrhtugecfsgng7k6npqtj678ndh50tp.apps.googleusercontent.com&redirect_uri=http%3A%2F%2Flocalhost%3A49350%2F&scope=https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive&state=I9XA0cXXq6yNSdJTNi1pnZIOW2TpPB&code_challenge=KJK-Ef4VCqtiAezWbO9iTy9x7qRpsK9OVVNJp8_DW14&code_challenge_method=S256&access_type=offline
Archivo subido: 1wrZsIdxo0-wRaeo7n2mDViVwiwWJGGRL
Please visit this URL to authorize this application: https://accounts.google.com/o/oauth2/auth?response_type=code&client_id=404263101909-0hrhtugecfsgng7k6npqtj678ndh50tp.apps.googleusercontent.com&redirect_uri=http%3A%2F%2Flocalhost%3A49359%2F&scope=https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive&state=tSf3d6M0ldAv0ttBBa3nMI984xmfkw&code_challenge=3ap55XANbrJ72iBHlR2JCUneifdNanMnjmfE90iLMNg&code_challenge_method=S256&access_type=offline
Archivo subido: 1KbKzgTBMq0wFVCmgBrZS8KvyFDiS8fEn
Please visit this URL to authorize this application: https://accounts.google.com/o/oauth2/auth?response_type=code&client_id=404263101909-0hrhtugecfsgng7k6npqtj678ndh50tp.apps.googleusercontent.com&redirect_uri=http%3A%2F%2Flocalhost%3A49368%2F&scope=https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive&state=9IcMjaN2shhfAl3b4J4vcXgayzfulz&code_challenge=dpex1MYX9w7T51niujyqx1gxDXB51yQLMoSLWogNDBg&code_challenge_method=S256&access_type=offline
Archivo subido: 126t_BL71gWFW1opFZRgq_ioqXhAeF6Xl

In [15]:
df_1 = pd.read_csv(str(path+csvs[0]))
df_2 = pd.read_csv(str(path+csvs[1]))
df_3 = pd.read_csv(str(path+csvs[2]))

In [27]:
ruta = '/Users/memoblack1/Documents/IA/4_semestre/ing_de_datos/ing_datos/bases/tabla_1.db'
nombre = 'data'
tools.sql.crear_db(df_1,ruta,nombre)

In [31]:
#Crear BD
ruta = '/Users/memoblack1/Documents/IA/4_semestre/ing_de_datos/ing_datos/bases/'
e=0
for i in csvs:
    e+=1
    new_path = str(path + i)
    df = pd.read_csv(new_path)
    print(new_path)
    new_ruta = ruta + f"tabla_{e}.db"
    print(new_ruta)
    nombre = 'data'
    tools.sql.crear_db(df=df, ruta_db=new_ruta, nombre_tabla=nombre)

/Users/memoblack1/Documents/IA/4_semestre/ing_de_datos/ing_datos/datasets/adilshamim8_salaries-for-data-science-jobs/salaries.csv
/Users/memoblack1/Documents/IA/4_semestre/ing_de_datos/ing_datos/bases/tabla_1.db
/Users/memoblack1/Documents/IA/4_semestre/ing_de_datos/ing_datos/datasets/samithsachidanandan_the-global-ai-ml-data-science-salary-for-2025/salaries.csv
/Users/memoblack1/Documents/IA/4_semestre/ing_de_datos/ing_datos/bases/tabla_2.db
/Users/memoblack1/Documents/IA/4_semestre/ing_de_datos/ing_datos/datasets/saurabhbadole_latest-data-science-job-salaries-2024/DataScience_salaries_2025.csv
/Users/memoblack1/Documents/IA/4_semestre/ing_de_datos/ing_datos/bases/tabla_3.db

In [32]:
#cargar db a drive
DB_DRIVE_FOLDER_ID = tools.DRIVE_IDS["DB_DRIVE_FOLDER_ID"]
tablas = ['tabla_1.db', 'tabla_2.db', 'tabla_3.db']
for i in tablas:
    tools.drive.cargar_archivo(DB_DRIVE_FOLDER_ID,str(ruta+i))

Please visit this URL to authorize this application: https://accounts.google.com/o/oauth2/auth?response_type=code&client_id=404263101909-0hrhtugecfsgng7k6npqtj678ndh50tp.apps.googleusercontent.com&redirect_uri=http%3A%2F%2Flocalhost%3A49461%2F&scope=https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive&state=KwMIYYw719XAmPxcCabLLnvENKf823&code_challenge=MkzyESzGIp9BWCinqBI6L0U3hhoPWG3q_oUw5jwJUPo&code_challenge_method=S256&access_type=offline
Archivo subido: 1BDhVSgHUtbFuNLF5st5WchpJKDfwuDVF
Please visit this URL to authorize this application: https://accounts.google.com/o/oauth2/auth?response_type=code&client_id=404263101909-0hrhtugecfsgng7k6npqtj678ndh50tp.apps.googleusercontent.com&redirect_uri=http%3A%2F%2Flocalhost%3A49471%2F&scope=https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive&state=3SGJcw5I9CIfVDLqTtrpTtV9hZcrJo&code_challenge=HJGbbpTBCimKmJ3Q9fDbvD1PmQ4VPJM_yfugs_4RR6E&code_challenge_method=S256&access_type=offline
Archivo subido: 1tbM0sMkC8OQ3oW3YKV_rNXFAdcK5BUgd
Please visit this URL to authorize this application: https://accounts.google.com/o/oauth2/auth?response_type=code&client_id=404263101909-0hrhtugecfsgng7k6npqtj678ndh50tp.apps.googleusercontent.com&redirect_uri=http%3A%2F%2Flocalhost%3A49480%2F&scope=https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive&state=4hI7Mloat0ZufgF17JxuuXU3nZJCEb&code_challenge=53JF0qXoLzsj4YHn0iLbE1ZCVCb89nhws5FiAPAMR_g&code_challenge_method=S256&access_type=offline
Archivo subido: 1R1oS-MIj125Gfqf2GojrAhxIjsq1BrNo

In [ ]:
dbs = {'tabla_1': '1BDhVSgHUtbFuNLF5st5WchpJKDfwuDVF',
       'tabla_2': '1tbM0sMkC8OQ3oW3YKV_rNXFAdcK5BUgd',
       'tabla_3': '1R1oS-MIj125Gfqf2GojrAhxIjsq1BrNo'}

In [34]:
#query desde drive
sql = "SELECT * from data"
tools.sql.query('1BDhVSgHUtbFuNLF5st5WchpJKDfwuDVF', sql)

Please visit this URL to authorize this application: https://accounts.google.com/o/oauth2/auth?response_type=code&client_id=404263101909-0hrhtugecfsgng7k6npqtj678ndh50tp.apps.googleusercontent.com&redirect_uri=http%3A%2F%2Flocalhost%3A49503%2F&scope=https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive&state=b9kdfPHhBwQruHXv6Ls9PSGNthTESl&code_challenge=0ca8QSS2LY8RsIA70KfqSDbX5Xj5k1b7fIymD_X8AT8&code_challenge_method=S256&access_type=offline

,work_year,experience_level,employment_type,job_title,salary,salary_currency,salary_in_usd,employee_residence,remote_ratio,company_location,company_size
0,2025,EX,FT,Head of Data,348516,USD,348516,US,0,US,M
1,2025,EX,FT,Head of Data,232344,USD,232344,US,0,US,M
2,2025,SE,FT,Data Scientist,145400,USD,145400,US,0,US,M
3,2025,SE,FT,Data Scientist,81600,USD,81600,US,0,US,M
4,2025,MI,FT,Engineer,160000,USD,160000,US,100,US,M
...,...,...,...,...,...,...,...,...,...,...,...
151440,2020,SE,FT,Data Scientist,412000,USD,412000,US,100,US,L
151441,2021,MI,FT,Principal Data Scientist,151000,USD,151000,US,100,US,L
151442,2020,EN,FT,Data Scientist,105000,USD,105000,US,100,US,S
151443,2020,EN,CT,Business Data Analyst,100000,USD,100000,US,100,US,L
151444,2021,SE,FT,Data Scientist,7000000,INR,94665,IN,50,IN,L

In [35]:
#query desde drive
sql = "SELECT * from data"
tools.sql.query('1tbM0sMkC8OQ3oW3YKV_rNXFAdcK5BUgd', sql)

Please visit this URL to authorize this application: https://accounts.google.com/o/oauth2/auth?response_type=code&client_id=404263101909-0hrhtugecfsgng7k6npqtj678ndh50tp.apps.googleusercontent.com&redirect_uri=http%3A%2F%2Flocalhost%3A49522%2F&scope=https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive&state=46X0l5Q0rcUqhqG6VjflzZ19tZQwxD&code_challenge=fEIZEOhGa7Zu3xgsCtFBkHR8F2zh_3pg8HuAh6SdkZc&code_challenge_method=S256&access_type=offline

,work_year,experience_level,employment_type,job_title,salary,salary_currency,salary_in_usd,employee_residence,remote_ratio,company_location,company_size
0,2025,MI,FT,Customer Success Manager,57000,EUR,60000,NL,50,NL,L
1,2025,SE,FT,Engineer,165000,USD,165000,US,0,US,M
2,2025,SE,FT,Engineer,109000,USD,109000,US,0,US,M
3,2025,SE,FT,Applied Scientist,294000,USD,294000,US,0,US,M
4,2025,SE,FT,Applied Scientist,137600,USD,137600,US,0,US,M
...,...,...,...,...,...,...,...,...,...,...,...
88579,2020,SE,FT,Data Scientist,412000,USD,412000,US,100,US,L
88580,2021,MI,FT,Principal Data Scientist,151000,USD,151000,US,100,US,L
88581,2020,EN,FT,Data Scientist,105000,USD,105000,US,100,US,S
88582,2020,EN,CT,Business Data Analyst,100000,USD,100000,US,100,US,L
88583,2021,SE,FT,Data Scientist,7000000,INR,94665,IN,50,IN,L

In [36]:
#query desde drive
sql = "SELECT * from data"
tools.sql.query('1R1oS-MIj125Gfqf2GojrAhxIjsq1BrNo', sql)

Please visit this URL to authorize this application: https://accounts.google.com/o/oauth2/auth?response_type=code&client_id=404263101909-0hrhtugecfsgng7k6npqtj678ndh50tp.apps.googleusercontent.com&redirect_uri=http%3A%2F%2Flocalhost%3A49534%2F&scope=https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive&state=VDyuEhFCAhGr4WaWBgsQ9pTu5WlNyy&code_challenge=mrZG_4uHXd8U6bFjlhNJgCQwTpnPaxDescZ4CNNQ33E&code_challenge_method=S256&access_type=offline

,work_year,experience_level,employment_type,job_title,salary,salary_currency,salary_in_usd,employee_residence,remote_ratio,company_location,company_size
0,2025,MI,FT,Research Scientist,208000,USD,208000,US,0,US,M
1,2025,MI,FT,Research Scientist,147000,USD,147000,US,0,US,M
2,2025,SE,FT,Research Scientist,173000,USD,173000,US,0,US,M
3,2025,SE,FT,Research Scientist,117000,USD,117000,US,0,US,M
4,2025,MI,FT,AI Engineer,100000,USD,100000,US,100,US,M
...,...,...,...,...,...,...,...,...,...,...,...
93592,2020,SE,FT,Data Scientist,412000,USD,412000,US,100,US,L
93593,2021,MI,FT,Principal Data Scientist,151000,USD,151000,US,100,US,L
93594,2020,EN,FT,Data Scientist,105000,USD,105000,US,100,US,S
93595,2020,EN,CT,Business Data Analyst,100000,USD,100000,US,100,US,L
93596,2021,SE,FT,Data Scientist,7000000,INR,94665,IN,50,IN,L